### ISSUE TITLE
Make it possible to use multiple filters on a dash

### ISSUE THREAD

**Issue by ArvindIntercom** [looker/looker-slackbot#34] opened 2016-03-29 22:40 UTC
Currently, it is not possible to set up a custom command that takes two or more arguments, corresponding to two or more filters on the dashboard. It would be very helpful if this functionality was added.

For example, let's say I have a dashboard that tracks the number of new customers. Currently, I can add a date filter, and ping Lookerbot by saying /looker dashboard this month. However, I can't add another filter beyond the date. If I wanted to get all new customers this month who were larger than $1,000, I can't say /looker this month >1000. 

Having the ability to pass multiple arguments into Lookerbot would be super helpful.

**Comment by wilg** [comment] 2016-03-29 23:58
Thanks @ArvindIntercom. This is a duplicate of #28, so I'm closing this in favor of that issue. We definitely want to figure out how to do this. It's a little tricky to figure out the right syntax for this, as mentioned on that issue. Would love suggestions!

**Closed by wilg** 2016-03-29 23:58 UTC

**Comment by ArvindIntercom** [comment] 2016-03-30 01:15
Hey Wil,

Maybe you could wrap the arguments in braces? 

For example:

1 filter with two inputs

/looker dashboard [arg1,arg2]

2 filters with 1 input each

/looker dashboard [arg1] [arg2]

Or maybe you could allow the user to specific the filter field to force looker to use specific filters:

1 filter titled ‘App Name’

/looker dashboard app_name: ‘Intercom’

2 filters titled ‘App Name’ and ‘Date Range’

/looker dashboard app_name: ‘Intercom’ date_range: ’this moth’ 

Just a couple ideas, excited to see where you guys take Lookerbot, people were definitely impressed!

-Arvind
